# Generated by Django 2.1.5 on 2019-11-23 15:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalbalance', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5)),
                ('youowe', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5)),
                ('youareowed', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='f_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='make_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='make_group',
            name='glist',
            field=models.ManyToManyField(to='splits.person'),
        ),
        migrations.AddField(
            model_name='friend',
            name='frnd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='splits.person'),
        ),
        migrations.AddField(
            model_name='f_list',
            name='frnd',
            field=models.ManyToManyField(to='splits.friend'),
        ),
        migrations.AddField(
            model_name='f_list',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='splits.person'),
        ),
        migrations.AddField(
            model_name='account',
            name='holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='splits.person'),
        ),
    ]
