# Generated by Django 2.2.4 on 2019-10-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make_groups',
            name='glist',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.DeleteModel(
            name='account',
        ),
        migrations.DeleteModel(
            name='make_groups',
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
