# Generated by Django 2.1.5 on 2019-11-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splits', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amt',
            field=models.FloatField(default=0),
        ),
    ]
