# Generated by Django 2.2.4 on 2019-10-17 04:38

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('splits', '0003_account_make_groups_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='make_groups',
            new_name='make_group',
        ),
    ]
