# Generated by Django 2.1.5 on 2019-11-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splits', '0004_auto_20191123_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='group',
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ManyToManyField(to='splits.make_group'),
        ),
    ]
