# Generated by Django 2.1.5 on 2019-11-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splits', '0005_auto_20191123_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='group',
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='splits.make_group'),
        ),
    ]
